name: Scheduled Workflow

on:
  workflow_dispatch:   # allows you to run manually
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes automatically

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print scheduled message
        run: echo "Scheduled workflow running"
